### ISSUE TITLE
TimeSeries doesn’t accept max_scale_value

### ISSUE THREAD

**Issue by FGasper** [ranguard/svg-tt-graph#10]

**Comment by ranguard** [comment]
Fixed by #11 - thanks!

@FGasper anything else you'd like to patch, or should I release to CPAN?

**Comment by FGasper** [comment]
On 14 Apr 2015 3:07 PM, Leo Lapworth wrote:
> Fixed by #11 <https://github.com/ranguard/svg-tt-graph/pull/11> - thanks!
>
> @FGasper <https://github.com/FGasper> anything else you'd like to patch,
> or should I release to CPAN?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ranguard/svg-tt-graph/issues/10#issuecomment-93044092>.
>

Those are just the things I needed to fix to work up a demo for my team. 
If you’re good with those changes, feel free to release.

Thank you! :)

-FG

**Comment by ranguard** [comment]
https://metacpan.org/release/LLAP/SVG-TT-Graph-0.25 :)
