### ISSUE TITLE
Pie segment labels are truncated

### ISSUE THREAD

**Issue by nelgin** [ranguard/svg-tt-graph#14]
When adding labels to a pie graph, I find that they sometimes get truncated if they are fairly long and to the right of the chart. From what I can tell, the width of the background isn't resized depending on the size of the actual chart image, and I don't see any way to overerite config.write with in the svg bg section.

You can see an example here:
http://toastmasterstest.sysadmininc.com/cgi-bin/memberspieorig.pl?district=50

I made a work around by changing line 389 of Pie.pm so the first config.width and config.height are config.bgwidth and config.bgheight respectively. I then added bgwidth and bgheight into the perl script and that did the trick.

http://toastmasterstest.sysadmininc.com/cgi-bin/memberspie.pl?district=50

You can see that the full label now fits.

So, the module either needs to recaculate the background based on the size of the image, or the user needs a way to manually control the background size, maybe using the method above.

Please consider this suggestion/issue for the next release.

**Comment by ranguard** [comment]
Hi @nelgin I'm not actively developing this module my self (I don't use it), but I'm happy to take patches and do releases.

**Comment by nelgin** [comment]
I have it working for my own limited use, but I am sure it may affect other things that I really don’t have the time or inclination to test.

 

Out of interest, if you developed/maintained the module but don’t use it, what are you using instead? Would it be better for me to move to something that’s not obsolete?

 

Thanks,

Nigel

**Comment by ranguard** [comment]
The project isn't dead, e.g. I take patches, but I don't have a need for SVG graphs in general.

I have used [Excel::Writer::XLSX](https://metacpan.org/pod/Excel::Writer::XLSX) for some stuff as well, the chart support there is now very good, but all depends what you want to do, I had to kick out reports for management and SVG wasn't going to work!

Good luck
