### ISSUE TITLE
Daylight savings time shifts are applied based on locale, regardless of entered timezone

### ISSUE THREAD

**Issue by elnjensen** [ranguard/svg-tt-graph#25]
Last night (March 11, 2018), my local timezone (U.S. Eastern time) switched from standard time to daylight savings time, meaning that the hour from 2 AM to 3 AM formally didn't exist in my local timezone; clocks jump from 1:59:59 AM to 3:00:00 AM.   Looking at some plots made with `SVG::TT::Graph::TimeSeries`, this jump is applied as well, even if I specify a value for `timescale_time_zone` that is a timezone with no daylight savings time (e.g. UTC). 

To show an example, here's a simple time series for the early morning hours for a day with *no* daylight savings time shift:

![test_nodst](https://user-images.githubusercontent.com/2545845/37261991-ad6a5896-2576-11e8-9626-c9b6c213481a.png)

and here is the same plot made for a night that does have a daylight savings time shift: 

![test_dst](https://user-images.githubusercontent.com/2545845/37261997-be1e6574-2576-11e8-97c7-9c464466f898.png)

As you can see, all of the 2 AM - 3 AM values are mapped into the 3 AM to 4 AM timeframe. 

Looking at the code, it appears to me that this is happening in `str2time` from `HTTP::Date`.   That module has limited support for timezones, but not in the full way that `DateTime` does (e.g. it only accepts "GMT" and numeric offsets, not timezones like "America/New_York"; it doesn't even handle "UTC" unless you explicitly do a `use Time::Zone` in the code before calling `str2time`).   

So an alternative might be to use `DateTime` for parsing the dates, since it is already loaded - but I'm not sure which of the `DateTime::Format` modules would be the right one, or if there would be unintended consequences of changing the date parsing. 

In the short term I guess I'll embed a "GMT" specification at the end of the time strings if I know I want UTC, but I do also have web-based use cases where the user might be in a timezone where the DST shift dates are different from those on the server, which could cause problems with no easy workaround. 

The test code to reproduce the above plots: 
```
#!/usr/bin/perl

# Minimal test example to show problem with 
# applying daylight savings time offsets regardless
# of timezone. 

use SVG::TT::Graph::TimeSeries;

my $print_html = 0;

my $ymd = '2018-03-11';

my @data_cpu = ("$ymd 01:00:00",54,
		"$ymd 01:15:00",54,
		"$ymd 01:30:00",54,
		"$ymd 01:45:00",54,
		"$ymd 02:00:00",67,
		"$ymd 02:15:00",67,
		"$ymd 02:30:00",67,
		"$ymd 02:45:00",67,
		"$ymd 03:00:00",77,
		"$ymd 03:15:00",77,
		"$ymd 03:30:00",77,
		"$ymd 03:45:00",77,
		"$ymd 04:00:00",87);

$timezone = 'UTC';

my $graph = SVG::TT::Graph::TimeSeries->new({
    'height' => '500',
    'width'  => '800',
    'timescale_divisions' => '1 hours',
    'timescale_time_zone' => $timezone,
					    });

$graph->add_data({
    'data'  => \@data_cpu,
    'title' => 'CPU',
		 });

$svg = $graph->burn();

# Simple if/then to either print straight
# SVG or wrap in HTML for viewing in browser: 
if ($print_html) {
    use CGI;
    $q = CGI->new();
    print $q->start_html();
    print "<div style=\"text-align: center\">\n";
    print $svg;
    print "</div>\n";
    print $q->end_html;
} else {
    print $svg;
}
```

**Comment by elnjensen** [comment]
Thinking about this a bit more, I wanted to add a couple of things.  First, in my example above, some of the dates passed in are nonsensical - the hours between 2:00 and 2:59 don't actually exist in my local timezone on the DST change date.  To be clear, I'm not trying to suggest that this module should support those (though it's interesting that it doesn't croak on them).  Second, it strikes me that there are two different ways (broadly) to tackle this: 

1.  More robust timezone support within the module itself, e.g. using the `timescale_time_zone` parameter to apply to the input times; or 
2. Simply clarifying in the docs that that parameter does not apply to how the input times are interpreted, and providing an example to show how the user can generate timezone-inclusive strings before passing them to the module.  From some brief experimenting, it looks like calling something like `DateTime::Format::RFC3339` on my DateTime objects before passing them in might do the trick. 

I'd be happy to consider working on a PR for this, but it would be useful to have some guidance on what you think the best approach would be before tackling it.

**Comment by ranguard** [comment]
Hi @elnjensen,

I'm afraid I didn't actually do the TimeSeries plugin that was @fangly I think (it's been a while!).

So I'm not really sure what to recommend, though I'd take a PR - I'd prefer it to be something I wouldn't have to worry breaks anything, this code it limited in tests! - e.g. option 2 - giving documentation and example of passing already cleaned data - has a lot going for it ;)

If that works for you then go for it! - if you'd rather spend the time on supporting timezones come back to me....

As a side note for work we now pay for https://www.highcharts.com/demo which you can actually use for free for non-commercial projects https://shop.highsoft.com/faq#Non-Commercial-0 might not fit your use case, but thought I'd mention it

**Comment by elnjensen** [comment]
OK, just opened a PR (#26) that should fix this, and also clarify in the docs what's needed to get plots in different timezones.  A small code change was needed - POSIX `strftime` is used for formatting the x-axis label, so that requires a prior call to POSIX `tzset` in order to set the timezone to anything other than that defined for the machine running the code.
