### ISSUE TITLE
SVG::TT::Graph::Bar rotate x-axis label to 45 degree

### ISSUE THREAD

**Issue by rpushker** [ranguard/svg-tt-graph#6]
Hi everyone,

I was wondering whether there is any way to rotate x-axis labels to anything other than 90 degrees. You have provided option 'rotate_x_labels' in SVG::TT::Graph::Bar->new method which can take only two values 0 or 1. There is no way to provide more values. 

Secondly, when you set 'rotate_x_labels' to 1, it rotates 90 degrees clockwise whereas it will look good if it is 90 degrees anticlockwise.

I checked the code Bar.pm;

Line 700 is

<text x="[% x + (dw / 2) - (bar_gap / 2) %]" y="[% base_line + 15 %]" [% IF config.rotate_x_labels %] transform="rotate(90 [% x + (dw / 2) - (bar_gap / 2) - half_char_height %] [% base_line + 15 %])" style="text-anchor: start"[% END %] class="xAxisLabels">[% field %]</text>

You have mentioned transform="rotate(90 ....." If we change 90 to 45 it will rotate by 45 degrees but the positioning won't be correct because of dw /2  - bar_gap/2 calculations.

Could you please suggest any solution for this?

With regards,
Pushker

**Comment by ranguard** [comment]
Closing for now until someone supplies a patch :)
